### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by bekirdag** [tiagosh/AltcoinGenerator#21]
Hello, 

I have built an ubuntu 16.04 machine, installed docker, changed the variables necessary and run the script. This is what I see at the end

```
Making all in src
make[1]: Entering directory '/nomoneylandcoin/src'
make[2]: Entering directory '/nomoneylandcoin/src'
  CXX      libbitcoinconsensus_la-arith_uint256.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory '/nomoneylandcoin/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
  CXX      nomoneylandcoind-bitcoind.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/nomoneylandcoin/src/secp256k1'
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-dbwrapper.o
  CXX      libbitcoin_server_a-merkleblock.o
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-net_processing.o
  CXX      libbitcoin_server_a-noui.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-rest.o
  CXX      script/libbitcoin_server_a-sigcache.o
  CXX      script/libbitcoin_server_a-ismine.o
  CXX      libbitcoin_server_a-timedata.o
  CXX      libbitcoin_server_a-torcontrol.o
  CXX      libbitcoin_server_a-txdb.o
  CXX      libbitcoin_server_a-txmempool.o
  CXX      libbitcoin_server_a-ui_interface.o
  CXX      libbitcoin_server_a-validation.o
  CXX      libbitcoin_server_a-validationinterface.o
  CXX      libbitcoin_server_a-versionbits.o
  CXX      libbitcoin_common_a-amount.o
  CXX      libbitcoin_common_a-base58.o
  CXX      libbitcoin_common_a-chainparams.o
chainparams.cpp: In constructor 'CMainParams::CMainParams()':
chainparams.cpp:117:38: error: expected primary-expression before ',' token
         genesis = CreateGenesisBlock(, , , 1, 50 * COIN);
                                      ^
chainparams.cpp:117:40: error: expected primary-expression before ',' token
         genesis = CreateGenesisBlock(, , , 1, 50 * COIN);
                                        ^
chainparams.cpp:117:42: error: expected primary-expression before ',' token
         genesis = CreateGenesisBlock(, , , 1, 50 * COIN);
                                          ^
chainparams.cpp: In constructor 'CTestNetParams::CTestNetParams()':
chainparams.cpp:220:50: error: expected primary-expression before ',' token
         genesis = CreateGenesisBlock(1486949366, , 0x1e0ffff0, 1, 50 * COIN);
                                                  ^
chainparams.cpp: In constructor 'CRegTestParams::CRegTestParams()':
chainparams.cpp:304:50: error: expected primary-expression before ',' token
         genesis = CreateGenesisBlock(1296688602, , 0x207fffff, 1, 50 * COIN);
                                                  ^
chainparams.cpp: At global scope:
chainparams.cpp:51:15: warning: 'CBlock CreateGenesisBlock(uint32_t, uint32_t, uint32_t, int32_t, const CAmount&)' defined but not used [-Wunused-function]
 static CBlock CreateGenesisBlock(uint32_t nTime, uint32_t nNonce, uint32_t nBits, int32_t nVersion, const CAmount& genesisReward)
               ^
Makefile:4910: recipe for target 'libbitcoin_common_a-chainparams.o' failed
make[2]: *** [libbitcoin_common_a-chainparams.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/nomoneylandcoin/src'
Makefile:8947: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/nomoneylandcoin/src'
Makefile:687: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
Creating docker network
3ef700c0e1c9df8a72dca046ce5fc871d36b2cdb7c64817b6e5a370f3cc1736a
Docker containers should be up and running now. You may run the following command to check the network status:
for i in $(docker ps -q); do docker exec $i /nomoneylandcoin/src/nomoneylandcoin-cli  getinfo; done
To ask the nodes to mine some blocks simply run:
for i in $(docker ps -q); do docker exec $i /nomoneylandcoin/src/nomoneylandcoin-cli  generate 2  & done
root@nmlcoin ~/nmlcoin # /bin/bash: ./src/nomoneylandcoind: No such file or directory
/bin/bash: ./src/nomoneylandcoind: No such file or directory
/bin/bash: ./src/nomoneylandcoind: No such file or directory
/bin/bash: ./src/nomoneylandcoind: No such file or directory
```
Also, when I run
```
for i in $(docker ps -q); do docker exec $i /nomoneylandcoin/src/nomoneylandcoin-cli  getinfo; done
```
it does not produce anything.

This is the server configuration:
```
root@nmlcoin ~/nmlcoin # uname -a
Linux nmlcoin 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

This is the configuration on the script:
```
COIN_NAME="NoMoneyLandCoin"
COIN_UNIT="NML"
# 42 million coins at total (litecoin total supply is 84000000)
TOTAL_SUPPLY=369444400
MAINNET_PORT="54321"
TESTNET_PORT="54322"
PHRASE="South Korean skater suffers wardrobe malfunction"
# First letter of the wallet address. Check https://en.bitcoin.it/wiki/Base58Check_encoding
PUBKEY_CHAR="10"
# number of blocks to wait to be able to spend coinbase UTXO's
COINBASE_MATURITY=10
# leave CHAIN empty for main network, -regtest for regression network and -testnet for test network
CHAIN=""
# this is the amount of coins to get as a reward of mining the block of height 1. if not set this will default to 50
PREMINED_AMOUNT=369440000

# warning: change this to your own pubkey to get the genesis block mining reward
GENESIS_REWARD_PUBKEY=MYSSHPUBKEY
```
Thank you.

**Comment by bekirdag** [comment]
This is also what happens when I run the script for the first time:

```
root@nmlcoin ~/nmlcoin # bash altcoin_generator.sh start
Docker image already built
~/nmlcoin/GenesisH0 ~/nmlcoin
Already up-to-date.
Mining genesis block... this procedure can take many hours of cpu work..
04ffff001d010430536f757468204b6f7265616e20736b6174657220737566666572732077617264726f6265206d616c66756e6374696f6e
Traceback (most recent call last):
  File "/GenesisH0/genesis.py", line 203, in <module>
    main()
  File "/GenesisH0/genesis.py", line 13, in main
    output_script = create_output_script(options.pubkey)
  File "/GenesisH0/genesis.py", line 69, in create_output_script
    return (script_len + pubkey + OP_CHECKSIG).decode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
Mining genesis block of test network... this procedure can take many hours of cpu work..
04ffff001d010430536f757468204b6f7265616e20736b6174657220737566666572732077617264726f6265206d616c66756e6374696f6e
Traceback (most recent call last):
  File "/GenesisH0/genesis.py", line 203, in <module>
    main()
  File "/GenesisH0/genesis.py", line 13, in main
    output_script = create_output_script(options.pubkey)
  File "/GenesisH0/genesis.py", line 69, in create_output_script
    return (script_len + pubkey + OP_CHECKSIG).decode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
Mining genesis block of regtest network... this procedure can take many hours of cpu work..
04ffff001d010430536f757468204b6f7265616e20736b6174657220737566666572732077617264726f6265206d616c66756e6374696f6e
Traceback (most recent call last):
  File "/GenesisH0/genesis.py", line 203, in <module>
    main()
  File "/GenesisH0/genesis.py", line 13, in main
    output_script = create_output_script(options.pubkey)
  File "/GenesisH0/genesis.py", line 69, in create_output_script
    return (script_len + pubkey + OP_CHECKSIG).decode('hex')
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
~/nmlcoin
Updating master branch
~/nmlcoin/litecoin-master ~/nmlcoin
Already up-to-date.
~/nmlcoin
Cloning into 'nomoneylandcoin'...
done.
~/nmlcoin/nomoneylandcoin ~/nmlcoin
~/nmlcoin
```

**Comment by tiagosh** [comment]
The genesis block generator failed: TypeError: Non-hexadecimal digit found.
From the logs, it seems to me that your pubkey might be in an invalid format.
Just for testing purposes, run "altcoin_generator.sh clean_up", revert to the original pubkey and check if the script runs fine.
If that works, I would suggest verifying your pubkey format, which should be in hexadecimal notation.

**Comment by bekirdag** [comment]
Yes, the script is working with the original pubkey. Can you suggest a way to generate the pubkey properly please?

**Comment by bekirdag** [comment]
Just for a note to the others, you should generate a PUBKEY from the https://github.com/lhartikk/GenesisH0 genesis.py script as described in the document. But I am still not sure how i will get that reward. I will note here after running the script. 

Thank you for the help.

**Comment by tiagosh** [comment]
For GenesisH0 to work you have to provide an uncompressed pubkey (65 bytes long).
1) Go to bitaddress.org
2) generate a new address
3) copy the private key
4) go to wallet details tab
5) paste private key and tap "view details"
6) Copy the first private key format named as : "Public Key (130 characters [0-9A-F]):"

This is the key you are looking for.
It is always recommended to download the generator and run it offline.

**Comment by bekirdag** [comment]
Thank you,

I have generated the coin with success and it's working like a charm. Thanks for the share, it saved me a lot of time.
